databases:
  - name: tarkov_api
    databaseName: tarkov_api
    user: tarkov_api

services:
  - type: web
    name: tarkov_api
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: tarkov_api
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false